name: Deploy Flask App to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Vercel CLI using npm
      run: |
        npm install -g vercel

    - name: Check if SECRET is set
      run: |
        if [ -z "${{ secrets.SECRET }}" ]; then echo "SECRET is not set"; else echo "SECRET is set"; fi

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.SECRET }}
      run: |
        vercel --token $SECRET --prod
